### ISSUE TITLE
Basicsr error? 

### ISSUE THREAD

**Issue by zelenooki87** [USTC-JialunPeng/RealSRT#1]
Do we need target images to run test? I want to upscale my own data.
Also please fix Basicsr:

`python inference_realsrt.py --input input --output results --model_path experiments/pretrained_models/net_g_80000.pth
Traceback (most recent call last):
  File "C:\Users\Miki\RealSRT\inference_realsrt.py", line 12, in <module>
    from realsrt.archs.realsrt_arch import RealSRT
  File "C:\Users\Miki\RealSRT\realsrt\__init__.py", line 2, in <module>
    from .archs import *
  File "C:\Users\Miki\RealSRT\realsrt\archs\__init__.py", line 2, in <module>
    from basicsr.utils import scandir
  File "C:\Users\Miki\RealSRT\basicsr\__init__.py", line 3, in <module>
    from .archs import *
  File "C:\Users\Miki\RealSRT\basicsr\archs\__init__.py", line 15, in <module>
    _arch_modules = [importlib.import_module(f'basicsr.archs.{file_name}') for file_name in arch_filenames]
  File "C:\Users\Miki\RealSRT\basicsr\archs\__init__.py", line 15, in <listcomp>
    _arch_modules = [importlib.import_module(f'basicsr.archs.{file_name}') for file_name in arch_filenames]
  File "C:\Users\Miki\anaconda3\envs\realsrt\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Miki\RealSRT\basicsr\archs\basicvsrpp_arch.py", line 7, in <module>
    from basicsr.archs.arch_util import flow_warp
  File "C:\Users\Miki\RealSRT\basicsr\archs\arch_util.py", line 13, in <module>
    from basicsr.ops.dcn import ModulatedDeformConvPack, modulated_deform_conv
ModuleNotFoundError: No module named 'basicsr.ops'`

**Comment by USTC-JialunPeng** [comment]
Bug fixed. 
Target images are not necessary, you can test your own data without them.

**Comment by profile838** [comment]
Thanks, new error:
python inference_realsrt.py --input input --output results --model_path experiments/pretrained_models/net_g_80000.pth
Traceback (most recent call last):
  File "C:\Users\Miki\RealSRT\inference_realsrt.py", line 12, in <module>
    from realsrt.archs.realsrt_arch import RealSRT
  File "C:\Users\Miki\RealSRT\realsrt\__init__.py", line 2, in <module>
    from .archs import *
  File "C:\Users\Miki\RealSRT\realsrt\archs\__init__.py", line 10, in <module>
    _arch_modules = [importlib.import_module(f'realsrt.archs.{file_name}') for file_name in arch_filenames]
  File "C:\Users\Miki\RealSRT\realsrt\archs\__init__.py", line 10, in <listcomp>
    _arch_modules = [importlib.import_module(f'realsrt.archs.{file_name}') for file_name in arch_filenames]
  File "C:\Users\Miki\anaconda3\envs\realsrt\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Miki\RealSRT\realsrt\archs\realsrt_arch.py", line 10, in <module>
    from .vqgan_arch import VQGAN, Encoder, ResidualBlock, AttnBlock
ImportError: cannot import name 'AttnBlock' from 'realsrt.archs.vqgan_arch' (C:\Users\Miki\RealSRT\realsrt\archs\vqgan_arch.py)

**Comment by USTC-JialunPeng** [comment]
Fixed. Sorry for my carelessness.

**Comment by profile838** [comment]
python inference_realsrt.py --input input/ --output results/ --model_path experiments/pretrained_models/net_g_80000.pth
Traceback (most recent call last):
  File "C:\Users\Miki\RealSRT\inference_realsrt.py", line 176, in <module>
    main()
  File "C:\Users\Miki\RealSRT\inference_realsrt.py", line 71, in main
    model = RealSRT(use_critic=True, use_ccm=True)
  File "C:\Users\Miki\RealSRT\realsrt\archs\realsrt_arch.py", line 363, in __init__
    self.generator = Transformer(
  File "C:\Users\Miki\RealSRT\realsrt\archs\realsrt_arch.py", line 249, in __init__
    pos_embed = get_2d_sincos_pos_embed(self.pos_emb.shape[-1], int(seq_len**.5))
  File "C:\Users\Miki\RealSRT\realsrt\archs\realsrt_arch.py", line 47, in get_2d_sincos_pos_embed
    pos_embed = get_2d_sincos_pos_embed_from_grid(embed_dim, grid)
  File "C:\Users\Miki\RealSRT\realsrt\archs\realsrt_arch.py", line 55, in get_2d_sincos_pos_embed_from_grid
    emb_h = get_1d_sincos_pos_embed_from_grid(embed_dim // 2, grid[0])  # (H*W, D/2)
  File "C:\Users\Miki\RealSRT\realsrt\archs\realsrt_arch.py", line 68, in get_1d_sincos_pos_embed_from_grid
    omega = np.arange(embed_dim // 2, dtype=np.float)
  File "C:\Users\Miki\anaconda3\envs\realsrt\lib\site-packages\numpy\__init__.py", line 338, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?




realsrt\archs\realsrt_arch.py
line 68
from:
`omega = np.arange(embed_dim // 2, dtype=np.float)`

to

`omega = np.arange(embed_dim // 2, dtype=float)`



Now working well. But slow :) On RTX 3090.

**Comment by USTC-JialunPeng** [comment]
I remember I used numpy<2.0.
What is the resolution you tested? How many seconds does it take to process one image?

**Comment by profile838** [comment]
around 70 seconds for input file 640x480
Results are nice :)
